language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: sJYrYezI9/wRhCkXRnWFYRvm358mD2m8ToJCqlkboeV8VyMcKQu55+t3TBnv/d5NsgTy2Q7fKPN2aBqRDBYphoReJAM2ogThalVG5ktubtdNYwigjLBTvQToSPNhzkBN7w8CW8W+c15/UQTvbPZzJ9DFYI5+EtAVH91YSeKG7bTsWp9pfJBmazAe2zbNPLADmOUDahqOaMbDjRVz0sugv0PFBlLDllxY4QzmNPBgiZUqYYp5N1hkTqKqcqVxeD5aEIKlLTL8HP3h4pHhpsWz7yFnK7ZixGoAYGahKLPaesDDaiUvzObADj0xWT9RNgLte2kSh87pSAYRqwbCROG7Pcv0tUtzKQCWQc9YW38fL+sS7NbefEZ9vRg3H57I7kYdJuCPD2rQrRF2slFrC7p7DvUL8bv/ONjq8Jw6yEskqOPDVlnjYipSdDWRlSUjv6h0ELybDVUd5ZYw9BdEUYhNsxDOv9wWwfy+pi9EC9FxJdyG3V/Ln+XgqbLn74Y3Oqua48n1vAymZGoLCaXgKySC5aapZMRcRWmcHLEMqj+tZXdnzR+dBBAqPVI+JhnKiJIMwME5MY6nfEMYyE9sbwFVpg8ueuu7px+/Xfx2NskfniMOyUKkZQWq4luBtCy1nUTsTSPTX4kNxY1n2t8HMx7or7PM3XaOtT1dNasAwtwCVb4=
  app: afternoon-badlands-72160
  on:
    repo: tardisdriver/travel_capstone
